name 'ectg-ucnext'
maintainer 'Steve Nolen'
maintainer_email 'technolengy@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures ectg-ucnext'
long_description 'Installs/Configures ectg-ucnext'
version '0.1.0'

depends 'ucnext'
depends 'elasticsearch'
depends 'mysql'
depends 'ruby_rbenv'
depends 'ruby_build'
depends 'nodejs'
depends 'nginx'
